export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const QUIZES_ROUTE = '/quiz'
export const QUIZ_CONSTRUCTOR_ROUTE = '/quiz'
